name: build-geodata
on:
  schedule:
    - cron: '0 22 * * *'        # 北京 06:00
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # ① 下载 dat
    - run: |
        BASE=https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download
        curl -fL $BASE/geoip.dat   -o geoip.dat
        curl -fL $BASE/geosite.dat -o geosite.dat

    # ② 下载 geoview（修正名）
    - run: |
        ARCH=$(uname -m)
        case "$ARCH" in
          x86_64)  FILE=geoview-linux-amd64  ;;
          aarch64) FILE=geoview-linux-arm64  ;;
          armv7l)  FILE=geoview-linux-armv7  ;;
        esac
        curl -fL https://github.com/snowie2000/geoview/releases/latest/download/$FILE -o geoview
        chmod +x geoview

    # ③ 解析 6 个 TXT
    - run: |
        ./geoview -type geoip   -input geoip.dat   -list cn,private \
                  -output geoip_cn.txt,geoip_private.txt
        ./geoview -type geosite -input geosite.dat \
                  -list cn,gfw,category-ads-all,geolocation-!cn \
                  -output geosite_cn.txt,geosite_gfw.txt,geosite_category-ads-all.txt,geosite_geolocation-!cn.txt

    # ④ 发布 Release
    - uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.run_number }}
        files: |
          geoip*.*
          geosite*.*
