name: build-geodata

on:
  schedule:
    - cron: '0 22 * * *'      # UTC 22:00 = 北京 06:00
  workflow_dispatch:

permissions:
  contents: write             # 解决 Release 403

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # 1. geoip.dat / geosite.dat
    - name: Download dat
      run: |
        set -eux
        base=https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download
        curl -fL $base/geoip.dat   -o geoip.dat
        curl -fL $base/geosite.dat -o geosite.dat

    # 2. geoview 二进制（资产名与你截图一致）
    - name: Download geoview
      run: |
        set -eux
        case "$(uname -m)" in
          x86_64)   f=geoview-linux-amd64   ;;
          aarch64)  f=geoview-linux-arm64   ;;
          armv7l)   f=geoview-linux-armv7   ;;
          armv6l)   f=geoview-linux-armv6   ;;
          armv5l)   f=geoview-linux-armv5   ;;
          i686|i386)f=geoview-linux-i386    ;;
          mips)     f=geoview-linux-mips    ;;
          mips64)   f=geoview-linux-mips64  ;;
          mips64el) f=geoview-linux-mips64le;;
          mipsle)   f=geoview-linux-mipsle  ;;
          riscv64)  f=geoview-linux-riscv64 ;;
          *) echo "unsupported arch"; exit 1 ;;
        esac
        curl -fL "https://github.com/snowie2000/geoview/releases/latest/download/$f" -o geoview
        chmod +x geoview

    # 3. 逐一生成 6 个 txt
    - name: Extract TXT files
      run: |
        set -eux
        ./geoview -type geoip   -input geoip.dat   -list cn        -output geoip_cn.txt
        ./geoview -type geoip   -input geoip.dat   -list private   -output geoip_private.txt
        ./geoview -type geosite -input geosite.dat -list cn        -output geosite_cn.txt
        ./geoview -type geosite -input geosite.dat -list gfw       -output geosite_gfw.txt
        ./geoview -type geosite -input geosite.dat -list category-ads-all      -output geosite_category-ads-all.txt
        ./geoview -type geosite -input geosite.dat -list geolocation-!cn       -output geosite_geolocation-!cn.txt

    # 4. 统一发布到 Release
    - name: Publish assets
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.run_number }}
        files: |
          geoip.dat
          geosite.dat
          geoip_cn.txt
          geoip_private.txt
          geosite_cn.txt
          geosite_gfw.txt
          geosite_category-ads-all.txt
          geosite_geolocation-!cn.txt
