name: build-geodata

# --- 触发事件 ---------------------------------------------------
on:
  schedule:
    - cron: '0 22 * * *'   # UTC 22:00 = 北京 06:00
  workflow_dispatch:

# --- 必要写权限：解决 403 ---------------------------------------
permissions:
  contents: write   # ← 关键！让默认 GITHUB_TOKEN 拥有 Release 写权限

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1) 下载 dat
    - name: Download dat
      run: |
        set -eux
        base=https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download
        curl -fL $base/geoip.dat   -o geoip.dat
        curl -fL $base/geosite.dat -o geosite.dat

    # 2) 下载 geoview（资产名与截图完全一致）
    - name: Download geoview
      run: |
        set -eux
        case "$(uname -m)" in
          x86_64)  fv=geoview-linux-amd64  ;;
          aarch64) fv=geoview-linux-arm64  ;;
          armv7l)  fv=geoview-linux-armv7  ;;
          armv6l)  fv=geoview-linux-armv6  ;;
          armv5l)  fv=geoview-linux-armv5  ;;
          i686|i386) fv=geoview-linux-i386 ;;
          mips)    fv=geoview-linux-mips   ;;
          mips64)  fv=geoview-linux-mips64 ;;
          mips64el)fv=geoview-linux-mips64le;;
          mipsle)  fv=geoview-linux-mipsle ;;
          riscv64) fv=geoview-linux-riscv64;;
          *) echo "unsupported arch"; exit 1;;
        esac
        curl -fL "https://github.com/snowie2000/geoview/releases/latest/download/$fv" -o geoview
        chmod +x geoview

    # 3) 解析 6 个 txt  (geoview 支持一次导出多文件，参数格式为 逗号分隔)
    - name: Extract txt
      run: |
        set -eux
        ./geoview -type geoip   -input geoip.dat   -list cn,private \
                  -output geoip_cn.txt,geoip_private.txt
        ./geoview -type geosite -input geosite.dat \
                  -list cn,gfw,category-ads-all,geolocation-!cn \
                  -output geosite_cn.txt,geosite_gfw.txt,geosite_category-ads-all.txt,geosite_geolocation-!cn.txt

    # 4) 创建 / 更新 Release 并上传 8 个文件
    - name: Publish release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.run_number }}
        files: |
          geoip.dat
          geosite.dat
          geoip_cn.txt
          geoip_private.txt
          geosite_cn.txt
          geosite_gfw.txt
          geosite_category-ads-all.txt
          geosite_geolocation-!cn.txt
